server:
  port: 8090

spring:
  application:
    name: voter-service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/voter
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true

  mvc:
    webjars:
      enabled: false  # Disable WebJars
  
  
  web:
    resources:
      add-mappings: false  

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

health:
  circuitbreakers:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      voter-service:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true
