pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Abdullaal7/Microservice-demo.git', branch: 'master'
            }
        }

        stage('Build Dependencies') {
            steps {
                script {
                    // Build the dependencies: eureka-server, config-server, and voter-db
                    bat "docker-compose -f docker-compose.yml up --build -d eureka-server config-server voter-db"
                }
            }
        }

        stage('Build Docker Image for Voter Service') {
            steps {
                script {
                    // Build voter-service after its dependencies
                    bat "docker-compose -f docker-compose.yml build voter-service"
                }
            }
        }

        stage('Tag and Push Voter Service Image') {
            steps {
                script {
                    bat "docker logout"
                    bat "docker login -u abdullaal77 -p #\$AaPwD56"

                    // Tag the image with the repository name and push it to Docker Hub
                    def imageName = "abdullaal77/voter-service:latest"
                    bat "docker tag voter-voter-service ${imageName}"
                    bat "docker push ${imageName}"
                }
            }
        }

        stage('Deploy Services') {
            steps {
                script {
                    // Start all dependencies and voter-service together
                    bat "docker-compose -f docker-compose.yml up -d eureka-server config-server voter-db voter-service"
                }
            }
        }
    }
}
